### ISSUE TITLE
Trying to access beyond buffer length

### ISSUE THREAD

**Issue by jomin398** [Kirkman/unityfs-asset-parser#1]
I used feross's buffer for html environment.
lz4 as lz4js.
abp is [index.js](./src/index.js)
(as es6 Wrapping, exports to export {} )

Here is error log.
```txt
Trying to access beyond buffer length
at x (https://cdn.jsdelivr.net/npm/buffer@6.0.3/+esm:13:12486)
at u.readInt32LE (https://cdn.jsdelivr.net/npm/buffer@6.0.3/+esm:13:16109)
at Parser.eval [as compiled] (eval at Parser.compile (http://localhost:7700/abp/binparse.js:286:21), <anonymous>:56:22)
at Parser.parse (http://localhost:7700/abp/binparse.js:338:17)
at parseAssetBundle (http://localhost:7700/abp/index.js:282:26)
at
```

asp file
```js
import { default as lz4js } from 'lz4';
import { Buffer } from 'buffer';
import * as dxt from './dxt.js';
import { default as Parser } from './binparse.js';
```

**Comment by jomin398** [comment]
run test.js on nodejs with orignal code.
here is error.
`Uncaught RangeError RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 20796. Received 20800`;
